# -*- coding: utf-8 -*-
"""cancer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N9kdtZ14KP8cF7xzW5NcAnxBKuroZO14
"""

import pandas as pd
from sklearn.linear_model import LinearRegression

bcd=pd.read_csv('/content/breast-cancer-dataset.csv')

bcd.head()

bcd.isnull().sum()

bcd.info()

bcd.dropna(inplace=True)

bcd.info()

from sklearn.preprocessing import LabelEncoder

LE=LabelEncoder()

bcd['BRE']=LE.fit_transform(bcd['Breast'])

bcd.tail()

LE1=LabelEncoder()

bcd['brq']=LE1.fit_transform(bcd['Breast Quadrant'])

bcd.head(10)

LE2=LabelEncoder()

bcd['DR']=LE2.fit_transform(bcd['Diagnosis Result'])

bcd.head()

LR=LinearRegression()

A=bcd[['Age','Menopause','Tumor Size (cm)','BRE','Metastasis','brq','History']]
B=bcd['DR']

LR.fit(A,B)

LR.predict([[40,1,2,2,0,3,0]])