# -*- coding: utf-8 -*-
"""Diabetes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SojX6YrxRneBFP_CAk-d1ltcNeYGXV96
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression

dia=pd.read_excel("/content/diabetes.xlsx")
dia.head()

dia.isnull().sum()

Logr=LogisticRegression()

ind=dia[['mass','insu','age','plas']]
dep=dia['class']

Logr.fit(ind,dep)

mass=int(input("Enter the mass"))
insu=int(input("Enter the insu"))
age=int(input("Enter the age"))
plas=int(input("Enter the plas"))
pred=Logr.predict([[mass,insu,age,plas]])
print(pred)

Logr.score(ind,dep)

from sklearn.metrics import accuracy_score
pval=Logr.predict(ind)
accuracy_score(dep,pval)