# -*- coding: utf-8 -*-
"""seaborn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sAr7zitWRvUCCdLvzbo43KlUPNYJYsXs
"""

import seaborn as sns
import matplotlib.pyplot as plt

tips=sns.load_dataset("tips")

tips

sns.scatterplot(x="total_bill",y="tip",data=tips)
plt.title("Scatter plot of Total Bill vs.tip ")
plt.xlabel("Total Bill")
plt.ylabel("Tip")
plt.show()

sns.lineplot(x="total_bill",y="tip",data=tips)
plt.title("Scatter plot of Total Bill vs.tip ")
plt.xlabel("Total Bill")
plt.ylabel("Tip")
plt.show()

sns.barplot(x="total_bill",y="tip",data=tips)
plt.title("Scatter plot of Total Bill vs.tip ")
plt.xlabel("Total Bill")
plt.ylabel("Tip")
plt.show()

sns.boxplot(x="total_bill",y="tip",data=tips)
plt.title("Scatter plot of Total Bill vs.tip ")
plt.xlabel("Total Bill")
plt.ylabel("Tip")
plt.show()

sns.violinplot(x="total_bill",y="tip",data=tips)
plt.title("Scatter plot of Total Bill vs.tip ")
plt.xlabel("Total Bill")
plt.ylabel("Tip")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

iris=sns.load_dataset("iris")
correlation_matrix=iris.drop('species', axis=1).corr()
sns.heatmap(correlation_matrix,annot=True,cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

ris=sns.load_dataset('iris')
sns.pairplot(iris,hue='species')
plt.show()

tips=sns.load_dataset("tips")
sns.jointplot(x='total_bill',y='tip',data=tips,kind="hex")
plt.title("Joint Distribution of Total Bill and Tip")
plt.xlabel("Total Bill ($)")
plt.ylabel("Tip($)")
plt.show()

titanic=sns.load_dataset("titanic")
sns.countplot(x="class",data=titanic)
plt.title("Distribution of Passenger Classes")
plt.xlabel("Passenger Class")
plt.ylabel("Count")
plt.show()